modifying terraform run

diff --git a/.github/workflows/terraform-run.yaml b/.github/workflows/terraform-run.yaml
--- a/.github/workflows/terraform-run.yaml
+++ b/.github/workflows/terraform-run.yaml
@@ -55,6 +55,20 @@ jobs:
                 echo "Pull request not originating from dev or stage branch, cannot determine workspace."
                 exit 1
               fi
+
+          elif [[ "${{ github.event_name }}" == 'push' ]]; then
+            # Extract the source branch name from the event
+            
+            LATESTLOG=$(git log -1 --pretty=%B)
+            SOURCE_BRANCH=$(echo $LATESTLOG | awk -F '\\\\n' '{print $1}' |  awk -F '/' '{print $2}' | awk '{print $1}')
+            if [[ "$SOURCE_BRANCH" == 'dev' ]]; then
+              WORKSPACE_NAME="$SOURCE_BRANCH"
+            elif [[ "$SOURCE_BRANCH" == 'stage' ]]; then
+              WORKSPACE_NAME="$SOURCE_BRANCH"
+            else
+              echo "Pull request not merged from dev branch to main, cannot determine workspace."
+              exit 1
+            fi
           fi
           
           echo "WORKSPACE_NAME=$WORKSPACE_NAME" >> $GITHUB_ENV
@@ -122,7 +136,7 @@ jobs:
         run: exit 1
 
       - name: Terraform Apply 
-        if: github.event_name == 'pull_request'
+        if: github.event_name == 'push'
         run: |
           
           if [[ "${{ env.WORKSPACE_NAME }}" == 'dev' ]]; then
@@ -135,7 +149,7 @@ jobs:
           terraform apply -auto-approve --var-file=$VAR_FILE
           
       - name: Terraform Destroy 
-        if: github.event_name == 'pull_request' 
+        if: github.event_name == 'push' 
         run: |
           if [[ "${{ env.WORKSPACE_NAME }}" == 'dev' ]]; then
             VAR_FILE='dev.tfvars'
